// <auto-generated />
using System;
using EDISWebApp;
using EDISWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EDISWebApp.Migrations
{
    [DbContext(typeof(EDISContext))]
    [Migration("20190424214705_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("EDISWebApp.Inventory", b =>
                {
                    b.Property<string>("StockNumber");

                    b.Property<string>("Brand");

                    b.Property<string>("ItemType");

                    b.Property<int>("ReorderPoint");

                    b.Property<int>("UnitsOnHand");

                    b.HasKey("StockNumber")
                        .HasName("Stock Number");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("EDISWebApp.Prescription", b =>
                {
                    b.Property<string>("RxNumber");

                    b.Property<DateTime>("LastRefillDate");

                    b.Property<int>("RefillsRemaining");

                    b.Property<string>("StockNumber");

                    b.HasKey("RxNumber")
                        .HasName("Prescription Number");

                    b.HasIndex("StockNumber");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("EDISWebApp.Prescription", b =>
                {
                    b.HasOne("EDISWebApp.Inventory", "StockNumberNavigation")
                        .WithMany("Prescription")
                        .HasForeignKey("StockNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
